#!/bin/sh

protected_branch="main"

echo "Checking if push to $protected_branch branch is allowed..."

set -e # exit if the script encounters an error

npm run lint

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_ref" = "refs/heads/$protected_branch" ]; then
            echo "Push to $protected_branch branch is not allowed."
            exit 1
    fi
done

exit 0
